//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTYT.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiSoDinhDuong
    {
        public int IdChiSoDinhDuong { get; set; }
        public Nullable<double> BMIMin { get; set; }
        public Nullable<double> BMIMax { get; set; }
        public string CanhBao { get; set; }
    }
}
