//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTYT.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTrieuChung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietTrieuChung()
        {
            this.ChiTietTiemChungs = new HashSet<ChiTietTiemChung>();
        }
    
        public int IdChiTietTrieuChung { get; set; }
        public Nullable<int> IdPhanUng { get; set; }
        public Nullable<int> IdTrieuChung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTiemChung> ChiTietTiemChungs { get; set; }
        public virtual TrieuChung TrieuChung { get; set; }
        public virtual PhanUng PhanUng { get; set; }
    }
}
