//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTYT.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKySuKien
    {
        public int IdDangKySuKien { get; set; }
        public Nullable<int> IdSuKien { get; set; }
        public string Email { get; set; }
        public string HoTen { get; set; }
        public string CCCD { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        public virtual SuKien SuKien { get; set; }
    }
}
