//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTYT.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTiemChung
    {
        public int IdLichTiemChung { get; set; }
        public Nullable<int> IdVacXin { get; set; }
        public Nullable<System.DateTime> NgayTiem { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
    
        public virtual VacXin VacXin { get; set; }
    }
}
