//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTYT.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKham
    {
        public int IdSoPhieu { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
        public Nullable<int> IdPhong { get; set; }
        public Nullable<int> IdBenhNhan { get; set; }
        public Nullable<int> IdThongTinThaiKy { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual ThongTinThaiKy ThongTinThaiKy { get; set; }
    }
}
