//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTYT.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int IDTK { get; set; }
        public Nullable<int> IDNV { get; set; }
        public string TenTK { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> IDQuyen { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
