//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTYT.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTTK_Me
    {
        public int IdTTTK_Me { get; set; }
        public Nullable<int> IdBenhNhan { get; set; }
        public Nullable<double> TuanTuoi { get; set; }
        public Nullable<double> ChieuDaiThaiNhi { get; set; }
        public Nullable<double> CanNangThaiNhi { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
    }
}
