<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyTramYTe" Class="QLTYTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=msi;Initial Catalog=QuanLyTramYTe;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanLyTramYTeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Benh" Member="Benhs">
    <Type Name="Benh">
      <Column Name="IdBenh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenBenh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Benh_VacXin" Member="VacXins" ThisKey="IdBenh" OtherKey="IdBenh" Type="VacXin" />
    </Type>
  </Table>
  <Table Name="dbo.VacXin" Member="VacXins">
    <Type Name="VacXin">
      <Column Name="IdVacXin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdBenh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenVacXin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LieuLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DonVi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoLo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="VacXin_ChiTietTiemChung" Member="ChiTietTiemChungs" ThisKey="IdVacXin" OtherKey="IdVacXin" Type="ChiTietTiemChung" />
      <Association Name="VacXin_LichTiemChung" Member="LichTiemChungs" ThisKey="IdVacXin" OtherKey="IdVacXin" Type="LichTiemChung" />
      <Association Name="Benh_VacXin" Member="Benh" ThisKey="IdBenh" OtherKey="IdBenh" Type="Benh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BenhNhan" Member="BenhNhans">
    <Type Name="BenhNhan">
      <Column Name="IdBenhNhan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdNhomBenhNhan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdGiaDinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BHYT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ChieuCao" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CanNang" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="BenhNhan_PhieuKham" Member="PhieuKhams" ThisKey="IdBenhNhan" OtherKey="IdBenhNhan" Type="PhieuKham" />
      <Association Name="BenhNhan_PhieuTiemChung" Member="PhieuTiemChungs" ThisKey="IdBenhNhan" OtherKey="IdBenhNhan" Type="PhieuTiemChung" />
      <Association Name="GiaDinh_BenhNhan" Member="GiaDinh" ThisKey="IdGiaDinh" OtherKey="IdGiaDinh" Type="GiaDinh" IsForeignKey="true" />
      <Association Name="NhomBenhNhan_BenhNhan" Member="NhomBenhNhan" ThisKey="IdNhomBenhNhan" OtherKey="IdNhomBenhNhan" Type="NhomBenhNhan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiSoDinhDuong" Member="ChiSoDinhDuongs">
    <Type Name="ChiSoDinhDuong">
      <Column Name="IdChiSoDinhDuong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BMIMin" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BMIMax" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CanhBao" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietTiemChung" Member="ChiTietTiemChungs">
    <Type Name="ChiTietTiemChung">
      <Column Name="IdChiTietTiemChung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdSoPhieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdChiTietTrieuChung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdVacXin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="VacXin_ChiTietTiemChung" Member="VacXin" ThisKey="IdVacXin" OtherKey="IdVacXin" Type="VacXin" IsForeignKey="true" />
      <Association Name="PhieuTiemChung_ChiTietTiemChung" Member="PhieuTiemChung" ThisKey="IdSoPhieu" OtherKey="IdSoPhieu" Type="PhieuTiemChung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietTrieuChung" Member="ChiTietTrieuChungs">
    <Type Name="ChiTietTrieuChung">
      <Column Name="IdChiTietTrieuChung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPhanUng" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTrieuChung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhanUng_ChiTietTrieuChung" Member="PhanUng" ThisKey="IdPhanUng" OtherKey="IdPhanUng" Type="PhanUng" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="TrieuChung_ChiTietTrieuChung" Member="TrieuChung" ThisKey="IdTrieuChung" OtherKey="IdTrieuChung" Type="TrieuChung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangKySuKien" Member="DangKySuKiens">
    <Type Name="DangKySuKien">
      <Column Name="IdDangKySuKien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdSuKien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SuKien_DangKySuKien" Member="SuKien" ThisKey="IdSuKien" OtherKey="IdSuKien" Type="SuKien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaDinh" Member="GiaDinhs">
    <Type Name="GiaDinh">
      <Column Name="IdGiaDinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChuHo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoNguoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="GiaDinh_BenhNhan" Member="BenhNhans" ThisKey="IdGiaDinh" OtherKey="IdGiaDinh" Type="BenhNhan" />
    </Type>
  </Table>
  <Table Name="dbo.LichTiemChung" Member="LichTiemChungs">
    <Type Name="LichTiemChung">
      <Column Name="IdLichTiemChung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdVacXin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTiem" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="VacXin_LichTiemChung" Member="VacXin" ThisKey="IdVacXin" OtherKey="IdVacXin" Type="VacXin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="IdLoaiPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiPhong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="IdLoaiPhong" OtherKey="IdLoaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="IdNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdNhomNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="NhanVien_PhieuKham" Member="PhieuKhams" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="PhieuKham" />
      <Association Name="NhanVien_PhieuTiemChung" Member="PhieuTiemChungs" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="PhieuTiemChung" />
      <Association Name="NhanVien_SuKien" Member="SuKiens" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="SuKien" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoans" ThisKey="IdNhanVien" OtherKey="IDNV" Type="TaiKhoan" />
      <Association Name="NhomNhanVien_NhanVien" Member="NhomNhanVien" ThisKey="IdNhomNhanVien" OtherKey="IdNhomNhanVien" Type="NhomNhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhomBenhNhan" Member="NhomBenhNhans">
    <Type Name="NhomBenhNhan">
      <Column Name="IdNhomBenhNhan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NhomBenhNhan_BenhNhan" Member="BenhNhans" ThisKey="IdNhomBenhNhan" OtherKey="IdNhomBenhNhan" Type="BenhNhan" />
    </Type>
  </Table>
  <Table Name="dbo.NhomNhanVien" Member="NhomNhanViens">
    <Type Name="NhomNhanVien">
      <Column Name="IdNhomNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhomNhanVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NhomNhanVien_NhanVien" Member="NhanViens" ThisKey="IdNhomNhanVien" OtherKey="IdNhomNhanVien" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyen" Member="PhanQuyens">
    <Type Name="PhanQuyen">
      <Column Name="IdQuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhanQuyen_TaiKhoan" Member="TaiKhoans" ThisKey="IdQuyen" OtherKey="IDQuyen" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.PhanUng" Member="PhanUngs">
    <Type Name="PhanUng">
      <Column Name="IdPhanUng" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhanUng" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MucDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhanUng_ChiTietTrieuChung" Member="ChiTietTrieuChungs" ThisKey="IdPhanUng" OtherKey="IdPhanUng" Type="ChiTietTrieuChung" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuKham" Member="PhieuKhams">
    <Type Name="PhieuKham">
      <Column Name="IdSoPhieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdBenhNhan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdThongTinThaiKy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="BenhNhan_PhieuKham" Member="BenhNhan" ThisKey="IdBenhNhan" OtherKey="IdBenhNhan" Type="BenhNhan" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuKham" Member="NhanVien" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Phong_PhieuKham" Member="Phong" ThisKey="IdPhong" OtherKey="IdPhong" Type="Phong" IsForeignKey="true" />
      <Association Name="ThongTinThaiKy_PhieuKham" Member="ThongTinThaiKy" ThisKey="IdThongTinThaiKy" OtherKey="IdThongTinThaiKy" Type="ThongTinThaiKy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuTiemChung" Member="PhieuTiemChungs">
    <Type Name="PhieuTiemChung">
      <Column Name="IdSoPhieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdBenhNhan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="PhieuTiemChung_ChiTietTiemChung" Member="ChiTietTiemChungs" ThisKey="IdSoPhieu" OtherKey="IdSoPhieu" Type="ChiTietTiemChung" />
      <Association Name="BenhNhan_PhieuTiemChung" Member="BenhNhan" ThisKey="IdBenhNhan" OtherKey="IdBenhNhan" Type="BenhNhan" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuTiemChung" Member="NhanVien" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Phong_PhieuTiemChung" Member="Phong" ThisKey="IdPhong" OtherKey="IdPhong" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="IdPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdLoaiPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Phong_PhieuKham" Member="PhieuKhams" ThisKey="IdPhong" OtherKey="IdPhong" Type="PhieuKham" />
      <Association Name="Phong_PhieuTiemChung" Member="PhieuTiemChungs" ThisKey="IdPhong" OtherKey="IdPhong" Type="PhieuTiemChung" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="IdLoaiPhong" OtherKey="IdLoaiPhong" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SuKien" Member="SuKiens">
    <Type Name="SuKien">
      <Column Name="IdSuKien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSuKien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="SuKien_DangKySuKien" Member="DangKySuKiens" ThisKey="IdSuKien" OtherKey="IdSuKien" Type="DangKySuKien" />
      <Association Name="NhanVien_SuKien" Member="NhanVien" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="IDTK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenTK" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IDQuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="IDNV" OtherKey="IdNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="PhanQuyen_TaiKhoan" Member="PhanQuyen" ThisKey="IDQuyen" OtherKey="IdQuyen" Type="PhanQuyen" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTinThaiKy" Member="ThongTinThaiKies">
    <Type Name="ThongTinThaiKy">
      <Column Name="IdThongTinThaiKy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TuanTuoi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ChieuDai" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CanNang" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ThongTinThaiKy_PhieuKham" Member="PhieuKhams" ThisKey="IdThongTinThaiKy" OtherKey="IdThongTinThaiKy" Type="PhieuKham" />
    </Type>
  </Table>
  <Table Name="dbo.TrieuChung" Member="TrieuChungs">
    <Type Name="TrieuChung">
      <Column Name="IdTrieuChung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTrieuChung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="TrieuChung_ChiTietTrieuChung" Member="ChiTietTrieuChungs" ThisKey="IdTrieuChung" OtherKey="IdTrieuChung" Type="ChiTietTrieuChung" />
    </Type>
  </Table>
</Database>